{{- if .Values.knative.eventing.local }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web3auth
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: web3auth
  dataFrom:
  - extract:
      key: /web3auth
{{- end }}