{{- if .Values.knative.eventing.local }}
{{- else }}
apiVersion: kubernetes-client.io/v1	
kind: ExternalSecret	
metadata:	
  name: web3auth
spec:	
  backendType: vault	
  vaultMountPoint: kubernetes	
  vaultRole: jx-vault
  data:
    - name: clientId
      key: secret/data/cloudnativeentrepreneur/{{ .Values.secretEnv }}/web3auth
      property: clientId
    - name: clientSecret
      key: secret/data/cloudnativeentrepreneur/{{ .Values.secretEnv }}/web3auth
      property: clientSecret
{{- end }}