{{- if .Values.knative.eventing.local }}
{{- else }}
{{- if .Values.knativeDeploy }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: {{ .Values.knative.minScale | quote }}
        autoscaling.knative.dev/maxScale: {{ .Values.knative.maxScale | quote }}
        autoscaling.knative.dev/target: {{ .Values.knative.concurrencyTarget | quote }}
{{- if .Values.podsLabels }}
      labels:
{{ toYaml .Values.podsLabels | indent 8 }}
{{- end }}
    spec:
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #           - key: serving.knative.dev/service
      #             operator: In
      #             values:
      #             - {{ .Values.service.name }}
      #         topologyKey: failure-domain.beta.kubernetes.io/zone
      #       weight: 100
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        env:
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.psql.username }}.{{ .Values.database.psql.name }}.credentials.postgresql.acid.zalan.do
              key: username
        - name: PG_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.psql.username }}.{{ .Values.database.psql.name }}.credentials.postgresql.acid.zalan.do
              key: password
        - name: PG_DATABASE
          value: {{ .Values.database.psql.database }}
        - name: PG_HOST
          value: {{ .Values.database.psql.hostname }}.{{ .Release.Namespace }}.svc.cluster.local
        - name: PG_PORT
          value: "5432"
        - name: PGSSLMODE
          value: no-verify
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: web3auth
              key: clientId
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: web3auth
              key: clientSecret
        - name: WEB3AUTH_EVENTS_BROKER_URL
          value: http://broker-ingress.knative-eventing.svc.cluster.local/{{ .Release.Namespace }}/web3auth-events
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
{{- end }}