apiVersion: v1
description: A Helm chart to run a web3 auth service to issue JWTs
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: web3auth-service
version: 0.1.0-SNAPSHOT
